name: deploy demo
on: [push]
jobs:
	deploy-demo:
		runs-on: ubuntu-latest
		steps:
		  - name: step 1
		  - uses: actions/checkout@v2
		  
		  - name step 2
		  - uses: actions/setup-node@v3
		    with:
			node-version: '14'
	
		  - name: step 3
		  - run: npm install -g bats
		  
		  - name: step 4
		  - run: bats -v 

